[package]

name = "producer_consumer"
version = "0.12.0"
authors = ["Krishna <https://github.com/krishnaIndia>"]
description = "The classic concurrency problem, in Rust."
license = "MIT"
repository = "https://gist.github.com/krishnaIndia/f037882b11aca172e9f2"